---
variables:
  - &golang_image 'docker.io/golang:1.24'
  - &cs3apivalidator_image 'owncloud/cs3api-validator:0.2.1'

when:
  - event: [ manual ]

workspace:
  base: /go # use the go home dir as workspace to share go packages, see https://woodpecker-ci.org/docs/usage/workflow-syntax#workspace

steps:
  wait_for_server:
    image: ghcr.io/dvjn/woodpecker-is-it-up-yet-plugin
    settings:
      host: revad-services
      port: 19000
  cs3api-validator-oci:
    image: *cs3apivalidator_image
    depends_on: [ wait_for_server ]
    commands:
      - /usr/bin/cs3api-validator /var/lib/cs3api-validator --endpoint=revad-services:19000

services:
  revad-services:
    image: *golang_image
    commands:
      - apt-get update -qq && apt-get install -y inotify-tools 
      - go build -o ./cmd/revad/revad ./cmd/revad
      - cd tests/oc-integration-tests/ci/
      - ../../../cmd/revad/revad -c frontend.toml &
      - ../../../cmd/revad/revad -c gateway.toml &
      - ../../../cmd/revad/revad -c storage-users-posix.toml &
      - ../../../cmd/revad/revad -c storage-shares.toml &
      - ../../../cmd/revad/revad -c storage-publiclink.toml &
      - ../../../cmd/revad/revad -c shares.toml &
      - ../../../cmd/revad/revad -c permissions-demo-ci.toml &
      - ../../../cmd/revad/revad -c users.toml